moto_principal_homepage:
    pattern:  /Inicio
    defaults: { _controller: MOTOPrincipalBundle:Default:index }

_login:
    pattern: /Login
    defaults: { _controller: MOTOPrincipalBundle:Login:Login }

_logout:
    pattern: /Logout
    defaults: { _controller: MOTOPrincipalBundle:Login:Logout }
    
_signup:
    pattern: /Signup
    defaults: { _controller: MOTOPrincipalBundle:Login:SignUp }

principal_administracion:
    pattern: /Admin
    defaults: { _controller: MOTOPrincipalBundle:Administracion:principalAdministracion }

asignar_dieta:
    pattern: /asignarDieta
    defaults: { _controller: MOTOPrincipalBundle:Administracion:asignarDieta }

crear_dieta:
    pattern: /crearDieta
    defaults: { _controller: MOTOPrincipalBundle:Administracion:crearDieta }
crear_dia_dieta:
    pattern: /crearDiaDieta
    defaults: { _controller: MOTOPrincipalBundle:Administracion:crearDiaDieta }
    
crear_plato:
    pattern: /crearPlato
    defaults: { _controller: MOTOPrincipalBundle:Administracion:crearPlato }

ver_dieta:
    pattern: /verDietaAdmin
    defaults: { _controller: MOTOPrincipalBundle:Administracion:verDieta }

asignar_tabla_cliente:
    pattern: /asignarTablaCliente
    defaults: { _controller: MOTOPrincipalBundle:Administracion:asignarTablaCliente }

nueva_tabla:
    pattern: /nuevaTabla
    defaults: { _controller: MOTOPrincipalBundle:Administracion:nuevaTabla }

nuevo_ejercicio:
    pattern: /nuevoEjercicio
    defaults: { _controller: MOTOPrincipalBundle:Administracion:nuevoEjercicio }

nuevo_empleado:
    pattern: /nuevoEmpleado
    defaults: { _controller: MOTOPrincipalBundle:Administracion:nuevoEmpleado }

gestionar_empleados:
    pattern: /gestionarEmpleados
    defaults: { _controller: MOTOPrincipalBundle:Administracion:gestionarEmpleados }

buscar_cliente:
    pattern: /buscarCliente
    defaults: { _controller: MOTOPrincipalBundle:Administracion:buscarCliente }
    
nueva_sesion:
    pattern: /nuevaSesion
    defaults: { _controller: MOTOPrincipalBundle:Administracion:nuevaSesion }

verDietas:
    pattern: /verDieta
    defaults: { _controller: MOTOPrincipalBundle:Default:verDieta }
    
verTablas:
    pattern: /verTabla
    defaults: { _controller: MOTOPrincipalBundle:Default:verTabla }   

modificarPlan:
    pattern: /modificarPlan
    defaults: { _controller: MOTOPrincipalBundle:Login:modificarPlan }   
    
insertProgreso:
    pattern: /insertProgreso
    defaults: { _controller: MOTOPrincipalBundle:Default:progreso }   
    
verResumenCliente:
    pattern: /verResumenCliente
    defaults: { _controller: MOTOPrincipalBundle:Default:verResumen } 
