parameters:
#    moto_principal.example.class: MOTO\PrincipalBundle\Example

services:
#    moto_principal.example:
#        class: %moto_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
